### ISSUE TITLE
Any plan to support code splitting?

### ISSUE THREAD

**Issue by lsm** [HenrikJoreteg/moonboots#64]
Our current bundled javascript file is almost 3MB and it's growing very fast and takes seconds to load. But, not all scripts are being used in all pages and load dependencies on-demand based on the requirement of page is kind of really necessary for javascript heavy project. Any plan to support this in the near future?

**Comment by lukekarrys** [comment]
Thanks for the question! So I'm not sure if it makes sense to bake this functionality into moonboots directly.

But since moonboots uses browserify under the hood it should be possible to use a browserify plugin like factor-bundle https://github.com/substack/factor-bundle to achieve at least some of the functionality you're asking about.

Unfortunately I've never used this plugin but I would be very interested to hear how it works in conjunction with moonboots.

---------
Luke Karrys

**Comment by lsm** [comment]
Yes, that's true. Code splitting is tied more to application structure. But, at least it might be helpful to add `watchify` to Moonboots and give user the option to regenerate bundles on change other than every request. It takes me couple seconds to generate the bundled javascript and I have to wait that time each time I refresh the browser. Like you said, since moonboots is based on browserify, it shouldn't very hard to add this feature to Moonboots. I'm using browserify directly now and following snippet works great for me:

```javascript
var b = browserify(inputFiles, opts);
b.plugin('factor-bundle', {
  outputs: outputFiles
});

var w = watchify(b);
w.on('log', function(msg) {
  console.log('Watchify:', msg);
});

w.on('update', writeBundle);
writeBundle();

function writeBundle() {
  w.bundle().pipe(fs.createWriteStream('public/assets/js/common.js'));
}
```

**Comment by lukekarrys** [comment]
Agreed that watchify would be a great addition! There's actually a pr that I need to check out which adds it  :) I'm hoping to get to it this week.

---------
Luke Karrys

**Comment by lsm** [comment]
That's great! Will keep eyes on it. Thanks for bring such great tools to the community, Ampersand etc.
